# Generated by Django 5.2 on 2025-04-09 16:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_question_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upvote',
            field=models.ManyToManyField(related_name='upvoted_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
